Fix type error in _customization_sso
Fixes below error:

  File "/usr/share/ovirt-engine/setup/bin/../plugins/ovirt-engine-setup/ovirt-engine-grafana-dwh/core/config.py", line 224, in _customization_sso
    f.write(res)
  TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Martin Perina <mperina@redhat.com>